<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="qrichtext" content="1" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body style=" font-family:'Consolas'; font-size:10pt; font-weight:400; font-style:normal;">
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Type &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.</p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">IPython 8.15.0 -- An enhanced Interactive Python.</p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#00ff00;">In [</span><span style=" font-weight:600; color:#00ff00;">1</span><span style=" color:#00ff00;">]:</span> runfile('C:/Users/Vigne/.spyder-py3/temp.py', wdir='C:/Users/Vigne/.spyder-py3')</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">[nltk_data] Downloading package punkt to</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">[nltk_data]     C:\Users\Vigne\AppData\Roaming\nltk_data...</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">[nltk_data]   Unzipping tokenizers\punkt.zip.</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">[nltk_data] Downloading package wordnet to</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">[nltk_data]     C:\Users\Vigne\AppData\Roaming\nltk_data...</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">[nltk_data] Downloading package omw-1.4 to</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">[nltk_data]     C:\Users\Vigne\AppData\Roaming\nltk_data...</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Training Data Shapes: X=(42, 77), Y=(42, 15)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Training new model...</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">C:\Users\Vigne\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">  super().__init__(activity_regularizer=activity_regularizer, **kwargs)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 1/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 2s 4ms/step - accuracy: 0.1056 - loss: 2.7127</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 2/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.0924 - loss: 2.6641     </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 3/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.1698 - loss: 2.6624 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 4/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.1982 - loss: 2.6365 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 5/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.1326 - loss: 2.6179     </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 6/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.3088 - loss: 2.5134 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 7/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.1821 - loss: 2.5091 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 8/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.2520 - loss: 2.4692 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 9/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.3430 - loss: 2.4255 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 10/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.2057 - loss: 2.3348 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 11/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.3083 - loss: 2.2040 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 12/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.4900 - loss: 2.2391 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 13/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.5071 - loss: 1.9719 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 14/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.4230 - loss: 2.0934 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 15/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.4011 - loss: 1.7968 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 16/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.5989 - loss: 1.6309 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 17/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.6224 - loss: 1.7884 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 18/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.5516 - loss: 1.4725 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 19/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.6427 - loss: 1.2437 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 20/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.5886 - loss: 1.3422 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 21/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.5539 - loss: 1.6166 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 22/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.7346 - loss: 1.1312 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 23/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.5833 - loss: 1.3709 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 24/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.7464 - loss: 1.1718 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 25/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.7963 - loss: 0.9857 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 26/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.6540 - loss: 1.0378 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 27/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9053 - loss: 0.7854 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 28/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.7225 - loss: 1.0228 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 29/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8156 - loss: 0.7300 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 30/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.5291 - loss: 1.1502 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 31/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8164 - loss: 0.8207 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 32/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8208 - loss: 0.7611 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 33/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.6669 - loss: 0.7542 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 34/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.6729 - loss: 0.7328 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 35/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.7907 - loss: 0.6253 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 36/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9590 - loss: 0.5253 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 37/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9009 - loss: 0.6048 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 38/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9630 - loss: 0.3472 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 39/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9554 - loss: 0.4621 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 40/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.8617 - loss: 0.4859 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 41/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8386 - loss: 0.5866 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 42/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9138 - loss: 0.4599 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 43/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8263 - loss: 0.5105 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 44/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.7777 - loss: 0.5508 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 45/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8429 - loss: 0.4247 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 46/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.8161 - loss: 0.4441 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 47/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9112 - loss: 0.4191 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 48/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9754 - loss: 0.3253 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 49/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.8504 - loss: 0.4861 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 50/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9151 - loss: 0.3545 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 51/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.7305 - loss: 0.4394 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 52/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8265 - loss: 0.4201 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 53/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8112 - loss: 0.3997 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 54/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9336 - loss: 0.2612 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 55/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.8298 - loss: 0.4481 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 56/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8883 - loss: 0.3044 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 57/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9162 - loss: 0.3287 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 58/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8223 - loss: 0.3675 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 59/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.7776 - loss: 0.4929 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 60/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9060 - loss: 0.2819  </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 61/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.8810 - loss: 0.3836 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 62/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9478 - loss: 0.1915 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 63/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9636 - loss: 0.2645 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 64/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9865 - loss: 0.1249 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 65/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8936 - loss: 0.3052 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 66/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9709 - loss: 0.1746 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 67/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9899 - loss: 0.1859 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 68/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8123 - loss: 0.4455 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 69/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9528 - loss: 0.2252 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 70/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.8519 - loss: 0.2741 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 71/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9609 - loss: 0.1392 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 72/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9608 - loss: 0.2895 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 73/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8945 - loss: 0.2950 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 74/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9255 - loss: 0.2616 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 75/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.8592 - loss: 0.4069 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 76/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9651 - loss: 0.1318 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 77/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8747 - loss: 0.3532 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 78/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9825 - loss: 0.1153 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 79/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9310 - loss: 0.2958 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 80/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8919 - loss: 0.2929 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 81/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9551 - loss: 0.2139 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 82/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9564 - loss: 0.1698 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 83/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0816 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 84/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9173 - loss: 0.2142 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 85/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9745 - loss: 0.1532 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 86/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8983 - loss: 0.2888 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 87/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9927 - loss: 0.1127 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 88/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9601 - loss: 0.1947 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 89/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.1001 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 90/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9038 - loss: 0.2017 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 91/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9521 - loss: 0.1972 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 92/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9927 - loss: 0.0980 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 93/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9674 - loss: 0.1429 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 94/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9184 - loss: 0.2131 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 95/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9434 - loss: 0.1461 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 96/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9506 - loss: 0.2991 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 97/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9952 - loss: 0.0446 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 98/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9234 - loss: 0.2199 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 99/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8893 - loss: 0.3338 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 100/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9609 - loss: 0.1921 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 101/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9899 - loss: 0.0940 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 102/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9724 - loss: 0.1503 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 103/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9798 - loss: 0.1527 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 104/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9609 - loss: 0.1467 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 105/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9143 - loss: 0.1694 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 106/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0703 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 107/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8843 - loss: 0.2131 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 108/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8735 - loss: 0.1974 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 109/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0705 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 110/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 1.0000 - loss: 0.0840 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 111/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9318 - loss: 0.2957 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 112/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9308 - loss: 0.2339 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 113/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9775 - loss: 0.1315 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 114/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9674 - loss: 0.1517 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 115/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9899 - loss: 0.1458 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 116/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9709 - loss: 0.1232 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 117/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9400 - loss: 0.1722 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 118/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9764 - loss: 0.1039 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 119/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.1394 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 120/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 1ms/step - accuracy: 1.0000 - loss: 0.0612 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 121/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9574 - loss: 0.1184 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 122/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9609 - loss: 0.2122 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 123/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0600 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 124/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9825 - loss: 0.0886 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 125/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 5ms/step - accuracy: 0.9661 - loss: 0.1198 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 126/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9473 - loss: 0.2318 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 127/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9508 - loss: 0.1365 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 128/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9927 - loss: 0.0517 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 129/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9574 - loss: 0.1813 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 130/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9775 - loss: 0.0780     </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 131/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0690 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 132/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9865 - loss: 0.0843 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 133/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9709 - loss: 0.0849 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 134/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9899 - loss: 0.0522 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 135/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9764 - loss: 0.0886 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 136/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9474 - loss: 0.1725 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 137/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9865 - loss: 0.0841 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 138/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9825 - loss: 0.0891 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 139/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9601 - loss: 0.1677 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 140/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0541 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 141/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8893 - loss: 0.2261 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 142/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0434 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 143/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.8726 - loss: 0.2362 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 144/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9825 - loss: 0.0981 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 145/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0183 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 146/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 1.0000 - loss: 0.0359 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 147/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9609 - loss: 0.1343 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 148/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9183 - loss: 0.1262 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 149/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0575 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 150/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9409 - loss: 0.1411 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 151/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0795 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 152/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9083 - loss: 0.1805 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 153/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9724 - loss: 0.0732 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 154/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9865 - loss: 0.0546 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 155/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9825 - loss: 0.0875 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 156/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9384 - loss: 0.1805 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 157/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9641 - loss: 0.2066 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 158/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9865 - loss: 0.0736 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 159/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9825 - loss: 0.0568 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 160/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9709 - loss: 0.0935 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 161/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0166 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 162/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9899 - loss: 0.0502 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 163/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9709 - loss: 0.1712 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 164/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9899 - loss: 0.1040 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 165/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9764 - loss: 0.0676 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 166/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0252 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 167/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0085 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 168/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9899 - loss: 0.0888 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 169/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0451 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 170/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0413 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 171/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 1.0000 - loss: 0.0633 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 172/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0907 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 173/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0390 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 174/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 4ms/step - accuracy: 0.9609 - loss: 0.0852 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 175/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9709 - loss: 0.0303 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 176/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9825 - loss: 0.0598 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 177/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.8826 - loss: 0.1373 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 178/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0378 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 179/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9927 - loss: 0.0522 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 180/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0352 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 181/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0281 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 182/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9825 - loss: 0.1074 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 183/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0450 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 184/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9899 - loss: 0.0399 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 185/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.1087 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 186/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0387 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 187/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0181 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 188/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.9336 - loss: 0.1538 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 189/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0218 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 190/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0399 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 191/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0323 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 192/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0552 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 193/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0102     </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 194/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0136 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 195/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0272 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 196/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 0.9899 - loss: 0.0470 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 197/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 2ms/step - accuracy: 1.0000 - loss: 0.0383 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 198/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0420 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 199/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 0.8683 - loss: 0.4537 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Epoch 200/200</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">9/9 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 3ms/step - accuracy: 1.0000 - loss: 0.0693 </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. </p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Chatbot is ready! Type 'exit' to stop.</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">You: HAI</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">1/1 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 168ms/step</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Bot: Hi! How can I help?</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">You: HOW ARE YOY</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">1/1 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 32ms/step</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Bot: I'm fine, thanks for asking!</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">You: TELL ME ABOUT CHATGPT</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">1/1 <span style=" color:#006400;">━━━━━━━━━━━━━━━━━━━━</span> 0s 47ms/step</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Bot: Python is a versatile programming language used in AI, data science, web development, and more.</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">You: </p></body></html>